### ISSUE TITLE
getting VerifyError when building with gradle

### ISSUE THREAD

**Issue by lwhiteley** [ralfebert/jgravatar#9]
VFY: invoke type does not match method type of Lcom/timgroup/jgravatar/Gravatar;.formatUrlParameters

``` java
07-21 02:03:26.338    1698-1698/com.forsafety.app I/Message:﹕ isAuthenticated? true
07-21 02:03:26.338    1698-1698/com.forsafety.app W/dalvikvm﹕ VFY: invoke type does not match method type of Lcom/timgroup/jgravatar/Gravatar;.formatUrlParameters
07-21 02:03:26.338    1698-1698/com.forsafety.app W/dalvikvm﹕ VFY:  rejecting opcode 0x6f at 0x001f
07-21 02:03:26.338    1698-1698/com.forsafety.app W/dalvikvm﹕ VFY:  rejected Lcom/timgroup/jgravatar/Gravatar;.getUrl (Ljava/lang/String;)Ljava/lang/String;
07-21 02:03:26.338    1698-1698/com.forsafety.app W/dalvikvm﹕ Verifier rejected class Lcom/timgroup/jgravatar/Gravatar;
07-21 02:03:26.338    1698-1698/com.forsafety.app D/AndroidRuntime﹕ Shutting down VM
07-21 02:03:26.338    1698-1698/com.forsafety.app W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xa4d73b20)
07-21 02:03:26.338    1698-1698/com.forsafety.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.forsafety.app, PID: 1698
    java.lang.VerifyError: com/timgroup/jgravatar/Gravatar
            at com.forsafety.app.activity.MainActivity.setGravatarImg(MainActivity.java:58)
            at com.forsafety.app.activity.MainActivity.onCreate(MainActivity.java:48)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)


```

the only difference between `formatUrlParameters` and other internal methods used is that it is set as a private method. Im wondering if anyone else is having this issue

**Comment by tigeratom59** [comment]
wondering if anyone else is having this issue
